import React from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, FileText, Scale, ShieldAlert, CheckCircle } from "lucide-react";
import { Footer } from "@/components/landing/Footer";

export const metadata: Metadata = {
  title: "TradeTracker Pro",
  description: "Read the Terms of Service for TradeTracker Pro outlining terms of platform usage, journals, calculators, and disclaimer of warranty.",
};

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground overflow-x-hidden pt-20">
      {/* ── Background Pattern ── */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden z-0">
        <div
          className="absolute inset-0 opacity-[0.02]"
          style={{
            backgroundImage: "radial-gradient(circle, currentColor 1px, transparent 1px)",
            backgroundSize: "24px 24px",
          }}
        />
        <div className="absolute top-20 left-1/2 -translate-x-1/2 w-[600px] h-[600px] rounded-full bg-primary/5 blur-[120px]" />
      </div>

      <div className="container relative z-10 mx-auto px-6 max-w-4xl flex-1 pb-20">
        {/* Back Link */}
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors mb-8 group"
        >
          <ArrowLeft className="w-3.5 h-3.5 group-hover:-translate-x-0.5 transition-transform" />
          Back to Homepage
        </Link>

        {/* Header */}
        <div className="mb-12">
          <div className="inline-flex items-center gap-1.5 rounded-full bg-primary/8 px-3.5 py-1 text-[11px] font-bold text-primary uppercase tracking-widest mb-4">
            <Scale className="w-3 h-3" /> Legal Center
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4">
            Terms of Service
          </h1>
          <p className="text-sm text-muted-foreground">
            Last updated: August 3, 2026
          </p>
        </div>

        {/* Content */}
        <div className="space-y-10 text-muted-foreground leading-relaxed text-sm sm:text-[15px]">
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
              <CheckCircle className="w-5 h-5 text-primary" /> 1. Acceptance of Terms
            </h2>
            <p>
              By signing up for an account, accessing, or using the services provided by <strong>TradeTracker Pro</strong>, you agree to comply with and be bound by these Terms of Service. If you do not agree to these terms, you are prohibited from utilizing the platform or any associated features.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
              <Scale className="w-5 h-5 text-primary" /> 2. Eligibility & Account Responsibilities
            </h2>
            <p>
              You must be at least 18 years of age (or the age of majority in your jurisdiction) to open an account. You agree to provide accurate and complete information during registration.
            </p>
            <p>
              You are entirely responsible for maintaining the confidentiality of your account credentials, passwords, and sessions. You agree to notify us immediately of any unauthorized use or breaches of security.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
              <ShieldAlert className="w-5 h-5 text-primary" /> 3. Risk & Financial Disclaimer
            </h2>
            <p>
              <strong>IMPORTANT:</strong> TradeTracker Pro is a journaling, backtesting, and trading analytics tool.
            </p>
            <ul className="list-disc pl-6 space-y-2 text-rose-500/90 font-medium">
              <li>We do not provide financial advice, trading signals, or investment recommendations.</li>
              <li>We do not execute trades, act as a broker-dealer, or handle live capital for trading purposes.</li>
              <li>Trading forex, gold, indices, commodities, stocks, and cryptocurrencies involves significant financial risk. You may lose some or all of your principal capital.</li>
            </ul>
            <p>
              All analytics, statistics (such as Win Rate, Profit Factor, Average R:R), and equity curves generated by the site are for educational, reflective, and analytics purposes only. Past performance does not guarantee future results.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
              <FileText className="w-5 h-5 text-primary" /> 4. Acceptable Use
            </h2>
            <p>
              You agree not to use the platform to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Upload malicious code, viruses, or exploit system vulnerabilities.</li>
              <li>Scrape, reverse engineer, or decompile any part of the site architecture or dashboards.</li>
              <li>Log fake, misleading, or abusive trade descriptions or content.</li>
              <li>Interfere with live market streaming sessions or other users&apos; access to the system.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
              <FileText className="w-5 h-5 text-primary" /> 5. Intellectual Property
            </h2>
            <p>
              All content, dashboards, logos, graphics, icons, visual components, database structures, and platform source codes are the intellectual property of TradeTracker Pro and are protected by international copyright and intellectual property laws. You are granted a limited, non-exclusive, non-transferable, revocable license to access and use the website for personal journaling purposes.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
              <Scale className="w-5 h-5 text-primary" /> 6. Limitation of Liability
            </h2>
            <p>
              In no event shall TradeTracker Pro, its owners, or partners be liable for any damages (including, without limitation, trading losses, loss of profits, data loss, or business interruption) arising out of the use of or inability to use the platform, even if notified of the possibility of such damage. The platform is provided on an &quot;as is&quot; and &quot;as available&quot; basis without warranties of any kind.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
              <FileText className="w-5 h-5 text-primary" /> 7. Governing Law & Modification
            </h2>
            <p>
              These terms shall be governed by and construed in accordance with the local laws, without regard to conflict of law provisions. We reserve the right to modify these Terms of Service at any time. Your continued use of the platform following the publication of changes signifies your acceptance of the updated terms.
            </p>
          </section>
        </div>
      </div>

      <Footer />
    </div>
  );
}
