import React from "react";
import Link from "next/link";
import type { Metadata } from "next";
import { Button } from "@/components/ui/button";
import {
  Globe,
  ArrowRight,
  Sparkles,
} from "lucide-react";
import { getOperatorTrades } from "@/lib/actions";
import { NavbarMobileMenu } from "@/components/landing/NavbarMobileMenu";
import { Footer } from "@/components/landing/Footer";
import { PublicSignalsClient } from "@/components/landing/PublicSignalsClient";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Operator HQ Signals & Track Record | TradeTracker Pro",
  description:
    "View live verified trading signals, win rate accuracy %, and total pips gained from Operator HQ. Completely public access with no login or verification required.",
};

export default async function PublicSignalsPage() {
  const session = await auth();
  const isLoggedIn = !!session?.user;
  const data = await getOperatorTrades();
  const stats = data?.stats || {
    totalSignals: 0,
    openSignals: 0,
    winCount: 0,
    lossCount: 0,
    closedCount: 0,
    accuracyPercent: 0,
    totalPips: 0,
  };
  const monthlyData = data?.monthlyData || [];
  const trades = data?.trades || [];

  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground overflow-x-hidden">
      {/* Navbar */}
      <header className="fixed top-0 left-0 right-0 z-50 border-b border-border/40 bg-background/80 backdrop-blur-2xl">
        <div className="container mx-auto max-w-7xl flex h-16 items-center justify-between px-6">
          <Link href="/" className="flex items-center group">
            <img
              src="/logo.png"
              className="h-12 w-auto select-none pointer-events-none"
              alt="TradeTracker Pro Logo"
            />
          </Link>
          <nav className="hidden md:flex items-center gap-1 text-sm">
            <Link
              href="/"
              className="px-3 py-1.5 rounded-md text-muted-foreground hover:text-foreground hover:bg-accent/50 transition-all"
            >
              Home
            </Link>
            <Link
              href="/signals"
              className="px-3 py-1.5 rounded-md text-foreground bg-accent/60 font-semibold transition-all"
            >
              Operator Signals
            </Link>
            <Link
              href="/#features"
              className="px-3 py-1.5 rounded-md text-muted-foreground hover:text-foreground hover:bg-accent/50 transition-all"
            >
              Features
            </Link>
          </nav>
          <div className="flex items-center gap-2.5">
            {isLoggedIn ? (
              <Button
                asChild
                size="sm"
                className="h-9 px-4 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg text-[13px] font-semibold shadow-xs shadow-primary/20"
              >
                <Link href="/dashboard">Go to Dashboard</Link>
              </Button>
            ) : (
              <>
                <Link
                  href="/auth/login"
                  className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors hidden sm:block"
                >
                  Sign in
                </Link>
                <Button
                  asChild
                  size="sm"
                  className="h-9 px-4 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg text-[13px] font-semibold shadow-xs shadow-primary/20"
                >
                  <Link href="/auth/sign-up">Get Started Free</Link>
                </Button>
              </>
            )}
            <NavbarMobileMenu isLoggedIn={isLoggedIn} />
          </div>
        </div>
      </header>

      {/* Hero Header */}
      <main className="flex-1 pt-24 md:pt-32 pb-16">
        <div className="container mx-auto max-w-7xl px-6">
          <div className="text-center max-w-3xl mx-auto mb-12">
            <div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3.5 py-1.5 text-xs font-bold text-primary mb-4 shadow-xs">
              <Sparkles className="w-3.5 h-3.5 text-primary" />
              Public Verified Signals Feed • No Login Required
            </div>

            <h1 className="text-3xl sm:text-5xl font-black tracking-tight leading-tight mb-4">
              Operator HQ Live Signals &amp; Accuracy Record
            </h1>

            <p className="text-sm sm:text-base text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              Transparent, real-time trade signal calls generated by our senior operators. Inspect our month-wise win rate accuracy, pip gains, and open trades without requiring any account login or verification.
            </p>
          </div>

          {/* Verification-Free Callout Banner */}
          <div className="mb-12 p-6 rounded-2xl bg-card/40 border border-primary/20 backdrop-blur-md relative overflow-hidden">
            <div className="absolute top-0 left-0 w-full h-[2px] bg-gold-gradient" />
            <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary shrink-0">
                  <Globe className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-sm font-bold uppercase tracking-wider text-foreground">
                    100% Free Public Access
                  </h3>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Anyone with this link can view real-time accuracy and trade executions without signing in or linking a broker account.
                  </p>
                </div>
              </div>
              <Button
                asChild
                className="bg-gold-gradient text-background hover:opacity-90 font-bold text-xs uppercase px-5 shrink-0"
              >
                {isLoggedIn ? (
                  <Link href="/dashboard">
                    Go to Dashboard <ArrowRight className="w-3.5 h-3.5 ml-1.5" />
                  </Link>
                ) : (
                  <Link href="/auth/sign-up">
                    Create Free Account <ArrowRight className="w-3.5 h-3.5 ml-1.5" />
                  </Link>
                )}
              </Button>
            </div>
          </div>

          {/* Interactive Monthwise Signals & Stats Client Component */}
          <PublicSignalsClient stats={stats} monthlyData={monthlyData} trades={trades} />
        </div>
      </main>

      <Footer />
    </div>
  );
}
