import React from "react";
import Link from "next/link";
import type { Metadata } from "next";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Award,
  TrendingUp,
  TrendingDown,
  Globe,
  ArrowRight,
  Sparkles,
} from "lucide-react";
import { getOperatorTrades } from "@/lib/actions";
import { NavbarMobileMenu } from "@/components/landing/NavbarMobileMenu";
import { Footer } from "@/components/landing/Footer";

export const metadata: Metadata = {
  title: "Operator HQ Signals & Track Record | TradeTracker Pro",
  description:
    "View live verified trading signals, win rate accuracy %, and total pips gained from Operator HQ. Completely public access with no login or verification required.",
};

export default async function PublicSignalsPage() {
  const data = await getOperatorTrades();
  const stats = data?.stats || {
    totalSignals: 0,
    openSignals: 0,
    winCount: 0,
    lossCount: 0,
    closedCount: 0,
    accuracyPercent: 0,
    totalPips: 0,
  };
  const trades = data?.trades || [];

  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground overflow-x-hidden">
      {/* Navbar */}
      <header className="fixed top-0 left-0 right-0 z-50 border-b border-border/40 bg-background/80 backdrop-blur-2xl">
        <div className="container mx-auto max-w-7xl flex h-16 items-center justify-between px-6">
          <Link href="/" className="flex items-center group">
            <img
              src="/logo.png"
              className="h-12 w-auto select-none pointer-events-none"
              alt="TradeTracker Pro Logo"
            />
          </Link>
          <nav className="hidden md:flex items-center gap-1 text-sm">
            <Link
              href="/"
              className="px-3 py-1.5 rounded-md text-muted-foreground hover:text-foreground hover:bg-accent/50 transition-all"
            >
              Home
            </Link>
            <Link
              href="/signals"
              className="px-3 py-1.5 rounded-md text-foreground bg-accent/60 font-semibold transition-all"
            >
              Operator Signals
            </Link>
            <Link
              href="/#features"
              className="px-3 py-1.5 rounded-md text-muted-foreground hover:text-foreground hover:bg-accent/50 transition-all"
            >
              Features
            </Link>
          </nav>
          <div className="flex items-center gap-2.5">
            <Link
              href="/auth/login"
              className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors hidden sm:block"
            >
              Sign in
            </Link>
            <Button
              asChild
              size="sm"
              className="h-9 px-4 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg text-[13px] font-semibold shadow-xs shadow-primary/20"
            >
              <Link href="/auth/sign-up">Get Started Free</Link>
            </Button>
            <NavbarMobileMenu />
          </div>
        </div>
      </header>

      {/* Hero Header */}
      <main className="flex-1 pt-24 md:pt-32 pb-16">
        <div className="container mx-auto max-w-7xl px-6">
          <div className="text-center max-w-3xl mx-auto mb-12">
            <div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3.5 py-1.5 text-xs font-bold text-primary mb-4 shadow-xs">
              <Sparkles className="w-3.5 h-3.5 text-primary" />
              Public Verified Signals Feed • No Login Required
            </div>

            <h1 className="text-3xl sm:text-5xl font-black tracking-tight leading-tight mb-4">
              Operator HQ Live Signals &amp; Accuracy Record
            </h1>

            <p className="text-sm sm:text-base text-muted-foreground max-w-2xl mx-auto leading-relaxed">
              Transparent, real-time trade signal calls generated by our senior operators. Inspect our historical win rate accuracy, pip gains, and open trades without requiring any account login or verification.
            </p>
          </div>

          {/* Verification-Free Callout Banner */}
          <div className="mb-12 p-6 rounded-2xl bg-card/40 border border-primary/20 backdrop-blur-md relative overflow-hidden">
            <div className="absolute top-0 left-0 w-full h-[2px] bg-gold-gradient" />
            <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary shrink-0">
                  <Globe className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-sm font-bold uppercase tracking-wider text-foreground">
                    100% Free Public Access
                  </h3>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Anyone with this link can view real-time accuracy and trade executions without signing in or linking a broker account.
                  </p>
                </div>
              </div>
              <Button
                asChild
                className="bg-gold-gradient text-background hover:opacity-90 font-bold text-xs uppercase px-5 shrink-0"
              >
                <Link href="/auth/sign-up">
                  Create Free Account <ArrowRight className="w-3.5 h-3.5 ml-1.5" />
                </Link>
              </Button>
            </div>
          </div>

          {/* Accuracy Stats Cards */}
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-12">
            <div className="p-6 rounded-2xl bg-card/50 border border-border/60 shadow-xs relative overflow-hidden">
              <div className="text-xs font-black uppercase tracking-widest text-muted-foreground mb-1">
                Win Rate Accuracy
              </div>
              <div className="text-4xl font-extrabold tracking-tight text-emerald-500 font-mono">
                {stats.accuracyPercent}%
              </div>
              <p className="text-[11px] text-muted-foreground mt-2">
                {stats.winCount} Wins / {stats.lossCount} Losses ({stats.closedCount} closed)
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-card/50 border border-border/60 shadow-xs">
              <div className="text-xs font-black uppercase tracking-widest text-muted-foreground mb-1">
                Total Pips Gained
              </div>
              <div className="text-4xl font-extrabold tracking-tight text-gold-gradient font-mono">
                {stats.totalPips > 0 ? `+${stats.totalPips}` : stats.totalPips}
              </div>
              <p className="text-[11px] text-muted-foreground mt-2">
                Cumulative pips across all signal calls
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-card/50 border border-border/60 shadow-xs">
              <div className="text-xs font-black uppercase tracking-widest text-muted-foreground mb-1">
                Total Signals Issued
              </div>
              <div className="text-4xl font-extrabold tracking-tight font-mono text-foreground">
                {stats.totalSignals}
              </div>
              <p className="text-[11px] text-muted-foreground mt-2">
                Active &amp; archived signal updates
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-card/50 border border-border/60 shadow-xs">
              <div className="text-xs font-black uppercase tracking-widest text-muted-foreground mb-1">
                Active Signals
              </div>
              <div className="text-4xl font-extrabold tracking-tight font-mono text-blue-400">
                {stats.openSignals}
              </div>
              <p className="text-[11px] text-muted-foreground mt-2">
                Currently open market trades
              </p>
            </div>
          </div>

          {/* Public Signal Feed */}
          <div className="space-y-6">
            <div className="flex items-center justify-between border-b border-border/40 pb-4">
              <div>
                <h2 className="text-xl font-extrabold tracking-tight">Public Trade Signals Log</h2>
                <p className="text-xs text-muted-foreground mt-0.5">
                  Real-time entries, stop loss, take profit, and exit pips performance
                </p>
              </div>
              <Badge className="bg-emerald-500/10 text-emerald-500 border-emerald-500/30 uppercase font-black text-[10px]">
                Live Feed
              </Badge>
            </div>

            {trades.length === 0 ? (
              <div className="p-12 text-center border border-dashed border-border/60 rounded-2xl bg-card/20">
                <Award className="w-10 h-10 text-primary mx-auto mb-3 opacity-60" />
                <h3 className="text-sm font-bold uppercase tracking-wider">No signals posted yet</h3>
                <p className="text-xs text-muted-foreground mt-1">
                  Operator signals will appear here as soon as our analysts post new setups.
                </p>
              </div>
            ) : (
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {trades.map((trade: any) => {
                  const isLong = trade.direction === "long";
                  const isTp = trade.status === "tp_hit";
                  const isSl = trade.status === "sl_hit";
                  const isOpen = trade.status === "open";

                  return (
                    <div
                      key={trade._id || trade.id}
                      className="p-5 rounded-xl bg-card/40 border border-border/60 hover:border-primary/40 transition-all flex flex-col justify-between space-y-4"
                    >
                      <div className="space-y-3">
                        {/* Symbol & Direction Header */}
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <Badge
                              className={
                                isLong
                                  ? "bg-emerald-500/10 text-emerald-500 border-emerald-500/30 font-bold"
                                  : "bg-rose-500/10 text-rose-500 border-rose-500/30 font-bold"
                              }
                            >
                              {isLong ? (
                                <TrendingUp className="w-3 h-3 mr-1" />
                              ) : (
                                <TrendingDown className="w-3 h-3 mr-1" />
                              )}
                              {trade.symbol} ({trade.direction.toUpperCase()})
                            </Badge>
                          </div>

                          {/* Status Badge */}
                          <Badge
                            variant="outline"
                            className={
                              isOpen
                                ? "bg-blue-500/10 text-blue-400 border-blue-500/30 font-bold text-[10px]"
                                : isTp
                                ? "bg-emerald-500/10 text-emerald-500 border-emerald-500/30 font-bold text-[10px]"
                                : isSl
                                ? "bg-rose-500/10 text-rose-500 border-rose-500/30 font-bold text-[10px]"
                                : "bg-muted text-muted-foreground text-[10px]"
                            }
                          >
                            {isOpen
                              ? "OPEN"
                              : isTp
                              ? "TP HIT"
                              : isSl
                              ? "SL HIT"
                              : trade.status.toUpperCase()}
                          </Badge>
                        </div>

                        {/* Trade Levels Grid */}
                        <div className="grid grid-cols-3 gap-2 bg-muted/30 p-2.5 rounded-lg text-xs font-mono">
                          <div>
                            <span className="text-[9px] uppercase text-muted-foreground block font-sans font-semibold">
                              Entry
                            </span>
                            <span className="font-bold text-foreground">{trade.entryPrice}</span>
                          </div>
                          <div>
                            <span className="text-[9px] uppercase text-muted-foreground block font-sans font-semibold">
                              Stop Loss
                            </span>
                            <span className="font-bold text-rose-400">{trade.stopLoss}</span>
                          </div>
                          <div>
                            <span className="text-[9px] uppercase text-muted-foreground block font-sans font-semibold">
                              Take Profit
                            </span>
                            <span className="font-bold text-emerald-400">{trade.takeProfit}</span>
                          </div>
                        </div>

                        {trade.notes && (
                          <p className="text-xs text-muted-foreground italic bg-muted/20 p-2 rounded border border-border/30">
                            &quot;{trade.notes}&quot;
                          </p>
                        )}
                      </div>

                      {/* Footer PnL & Timestamp */}
                      <div className="pt-3 border-t border-border/40 flex items-center justify-between text-xs font-mono">
                        <span className="text-[10px] text-muted-foreground font-sans">
                          {new Date(trade.createdAt).toLocaleDateString("en-US", {
                            month: "short",
                            day: "numeric",
                            hour: "2-digit",
                            minute: "2-digit",
                          })}
                        </span>
                        <div className="font-bold">
                          {trade.pnlPips > 0 ? (
                            <span className="text-emerald-500">+{trade.pnlPips} Pips</span>
                          ) : trade.pnlPips < 0 ? (
                            <span className="text-rose-500">{trade.pnlPips} Pips</span>
                          ) : (
                            <span className="text-muted-foreground">0 Pips</span>
                          )}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
